const dict = {
  es: {
    loading: "CARGANDO...",
    btn_google: "Continuar con Google",
    btn_email: "Correo y Contraseña",
    btn_guest: "Continuar sin conectarse",
    lbl_email: "CORREO ELECTRÓNICO",
    plc_email: "tu@correo.com",
    lbl_password: "CONTRASEÑA",
    plc_password: "******",
    btn_login: "ENTRAR",
    btn_register: "CREAR",
    btn_back: "← Volver",
    lbl_name: "TU NOMBRE",
    plc_name: "ej: Manuel",
    btn_login_anon: "ENTRAR ANÓNIMO",
    offline_banner: "SIN CONEXIÓN",
    receipt_title: "—— LISTA DE COMPRAS ——",
    lbl_add_item: "+ NUEVO ITEM",
    plc_item_name: "producto…",
    plc_item_price: "precio",
    plc_item_qty: "cant.",
    btn_add: "AGREGAR ›",
    empty_list: "— LISTA VACÍA —",
    lbl_subtotal: "SUBTOTAL",
    lbl_items: "ITEMS",
    lbl_open: "ABIERTA",
    lbl_discount: "DESCUENTO",
    lbl_total: "TOTAL",
    lbl_budget: "PRESUPUESTO MENSUAL",
    btn_finish: "TERMINAR COMPRA",
    receipt_footer: "★ ★ ★ GRACIAS POR USAR LISTBUY ★ ★ ★",
    btn_logout: "Cerrar sesión",
    btn_settings: "Configuración",
    title_history: "Historial",
    title_budget: "Presupuesto",
    title_compare: "Comparar precios",
    title_ticket: "Tu ticket",
    btn_copy: "Copiar",
    btn_whatsapp: "WhatsApp →",
    lbl_archive: "ARCHIVAR COMPRA",
    plc_store: "Nombre del local (ej: Coto, Disco…)",
    btn_save_history: "GUARDAR EN HISTORIAL",
    lbl_edit_item: "EDITAR ITEM",
    btn_save: "GUARDAR",
    err_fill_all: "Completa correo y contraseña",
    err_login: "Error: ",
    alert_copied: "Copiado al portapapeles",
    alert_undo: "Deshacer",
    alert_deleted: "eliminado",
    confirm_del_history: "¿Borrar este registro del historial?",
    btn_cancel: "Cancelar",
    btn_delete: "Sí, borrar",
    lbl_language: "IDIOMA",
    lbl_currency: "MONEDA",
    btn_clear_cache: "BORRAR CACHÉ LOCAL",
    settings_title: "Ajustes",
    lbl_theme: "TEMA VISUAL",
    theme_light: "Claro",
    theme_dark: "Oscuro"
  },
  en: {
    loading: "LOADING...",
    btn_google: "Continue with Google",
    btn_email: "Email and Password",
    btn_guest: "Continue as Guest",
    lbl_email: "EMAIL",
    plc_email: "you@email.com",
    lbl_password: "PASSWORD",
    plc_password: "******",
    btn_login: "LOGIN",
    btn_register: "REGISTER",
    btn_back: "← Back",
    lbl_name: "YOUR NAME",
    plc_name: "eg: John",
    btn_login_anon: "ENTER GUEST",
    offline_banner: "OFFLINE",
    receipt_title: "—— SHOPPING LIST ——",
    lbl_add_item: "+ NEW ITEM",
    plc_item_name: "product…",
    plc_item_price: "price",
    plc_item_qty: "qty.",
    btn_add: "ADD ›",
    empty_list: "— EMPTY LIST —",
    lbl_subtotal: "SUBTOTAL",
    lbl_items: "ITEMS",
    lbl_open: "OPEN",
    lbl_discount: "DISCOUNT",
    lbl_total: "TOTAL",
    lbl_budget: "MONTHLY BUDGET",
    btn_finish: "FINISH SHOPPING",
    receipt_footer: "★ ★ ★ THANKS FOR USING LISTBUY ★ ★ ★",
    btn_logout: "Log out",
    btn_settings: "Settings",
    title_history: "History",
    title_budget: "Budget",
    title_compare: "Compare prices",
    title_ticket: "Your ticket",
    btn_copy: "Copy",
    btn_whatsapp: "WhatsApp →",
    lbl_archive: "ARCHIVE RECEIPT",
    plc_store: "Store name (eg: Walmart, Target…)",
    btn_save_history: "SAVE TO HISTORY",
    lbl_edit_item: "EDIT ITEM",
    btn_save: "SAVE",
    err_fill_all: "Fill email and password",
    err_login: "Error: ",
    alert_copied: "Copied to clipboard",
    alert_undo: "Undo",
    alert_deleted: "deleted",
    confirm_del_history: "Delete this record from history?",
    btn_cancel: "Cancel",
    btn_delete: "Yes, delete",
    lbl_language: "LANGUAGE",
    lbl_currency: "CURRENCY",
    btn_clear_cache: "CLEAR LOCAL CACHE",
    settings_title: "Settings",
    lbl_theme: "THEME",
    theme_light: "Light",
    theme_dark: "Dark"
  },
  it: {
    loading: "CARICAMENTO...",
    btn_google: "Continua con Google",
    btn_email: "Email e Password",
    btn_guest: "Continua come Ospite",
    lbl_email: "EMAIL",
    plc_email: "tu@email.com",
    lbl_password: "PASSWORD",
    plc_password: "******",
    btn_login: "ACCEDI",
    btn_register: "REGISTRATI",
    btn_back: "← Indietro",
    lbl_name: "IL TUO NOME",
    plc_name: "es: Marco",
    btn_login_anon: "ENTRA OSPITE",
    offline_banner: "OFFLINE",
    receipt_title: "—— LISTA DELLA SPESA ——",
    lbl_add_item: "+ NUOVO ARTICOLO",
    plc_item_name: "prodotto…",
    plc_item_price: "prezzo",
    plc_item_qty: "q.tà",
    btn_add: "AGGIUNGI ›",
    empty_list: "— LISTA VUOTA —",
    lbl_subtotal: "SUBTOTALE",
    lbl_items: "ARTICOLI",
    lbl_open: "APERTA",
    lbl_discount: "SCONTO",
    lbl_total: "TOTALE",
    lbl_budget: "BUDGET MENSILE",
    btn_finish: "TERMINA SPESA",
    receipt_footer: "★ ★ ★ GRAZIE PER USARE LISTBUY ★ ★ ★",
    btn_logout: "Esci",
    btn_settings: "Impostazioni",
    title_history: "Cronologia",
    title_budget: "Budget",
    title_compare: "Confronta prezzi",
    title_ticket: "Il tuo scontrino",
    btn_copy: "Copia",
    btn_whatsapp: "WhatsApp →",
    lbl_archive: "ARCHIVIA SPESA",
    plc_store: "Nome negozio (es: Esselunga…)",
    btn_save_history: "SALVA NELLA CRONOLOGIA",
    lbl_edit_item: "MODIFICA ARTICOLO",
    btn_save: "SALVA",
    err_fill_all: "Inserisci email e password",
    err_login: "Errore: ",
    alert_copied: "Copiato negli appunti",
    alert_undo: "Annulla",
    alert_deleted: "eliminato",
    confirm_del_history: "Eliminare questo record dalla cronologia?",
    btn_cancel: "Annulla",
    btn_delete: "Sì, elimina",
    lbl_language: "LINGUA",
    lbl_currency: "VALUTA",
    btn_clear_cache: "CANCELLA CACHE LOCALE",
    settings_title: "Impostazioni",
    lbl_theme: "TEMA",
    theme_light: "Chiaro",
    theme_dark: "Scuro"
  },
  pt: {
    loading: "CARREGANDO...",
    btn_google: "Continuar com o Google",
    btn_email: "E-mail e Senha",
    btn_guest: "Continuar como Convidado",
    lbl_email: "E-MAIL",
    plc_email: "voce@email.com",
    lbl_password: "SENHA",
    plc_password: "******",
    btn_login: "ENTRAR",
    btn_register: "CRIAR",
    btn_back: "← Voltar",
    lbl_name: "SEU NOME",
    plc_name: "ex: João",
    btn_login_anon: "ENTRAR COMO CONVIDADO",
    offline_banner: "OFFLINE",
    receipt_title: "—— LISTA DE COMPRAS ——",
    lbl_add_item: "+ NOVO ITEM",
    plc_item_name: "produto…",
    plc_item_price: "preço",
    plc_item_qty: "qtd.",
    btn_add: "ADICIONAR ›",
    empty_list: "— LISTA VAZIA —",
    lbl_subtotal: "SUBTOTAL",
    lbl_items: "ITENS",
    lbl_open: "ABERTA",
    lbl_discount: "DESCONTO",
    lbl_total: "TOTAL",
    lbl_budget: "ORÇAMENTO MENSAL",
    btn_finish: "FINALIZAR COMPRA",
    receipt_footer: "★ ★ ★ OBRIGADO POR USAR LISTBUY ★ ★ ★",
    btn_logout: "Sair",
    btn_settings: "Configurações",
    title_history: "Histórico",
    title_budget: "Orçamento",
    title_compare: "Comparar preços",
    title_ticket: "Seu recibo",
    btn_copy: "Copiar",
    btn_whatsapp: "WhatsApp →",
    lbl_archive: "ARQUIVAR COMPRA",
    plc_store: "Nome da loja (ex: Carrefour…)",
    btn_save_history: "SALVAR NO HISTÓRICO",
    lbl_edit_item: "EDITAR ITEM",
    btn_save: "SALVAR",
    err_fill_all: "Preencha e-mail e senha",
    err_login: "Erro: ",
    alert_copied: "Copiado para a área de transferência",
    alert_undo: "Desfazer",
    alert_deleted: "removido",
    confirm_del_history: "Apagar este registro do histórico?",
    btn_cancel: "Cancelar",
    btn_delete: "Sim, apagar",
    lbl_language: "IDIOMA",
    lbl_currency: "MOEDA",
    btn_clear_cache: "LIMPAR CACHE LOCAL",
    settings_title: "Configurações",
    lbl_theme: "TEMA VISUAL",
    theme_light: "Claro",
    theme_dark: "Escuro"
  },
  fr: {
    loading: "CHARGEMENT...",
    btn_google: "Continuer avec Google",
    btn_email: "Email et Mot de passe",
    btn_guest: "Continuer sans inscription",
    lbl_email: "EMAIL",
    plc_email: "vous@email.com",
    lbl_password: "MOT DE PASSE",
    plc_password: "******",
    btn_login: "CONNEXION",
    btn_register: "CRÉER",
    btn_back: "← Retour",
    lbl_name: "VOTRE NOM",
    plc_name: "ex: Jean",
    btn_login_anon: "ENTRER INVITÉ",
    offline_banner: "HORS LIGNE",
    receipt_title: "—— LISTE DE COURSES ——",
    lbl_add_item: "+ NOUVEL ARTICLE",
    plc_item_name: "produit…",
    plc_item_price: "prix",
    plc_item_qty: "qté.",
    btn_add: "AJOUTER ›",
    empty_list: "— LISTE VIDE —",
    lbl_subtotal: "SOUS-TOTAL",
    lbl_items: "ARTICLES",
    lbl_open: "OUVERTE",
    lbl_discount: "RÉDUCTION",
    lbl_total: "TOTAL",
    lbl_budget: "BUDGET MENSUEL",
    btn_finish: "TERMINER LES COURSES",
    receipt_footer: "★ ★ ★ MERCI D'UTILISER LISTBUY ★ ★ ★",
    btn_logout: "Déconnexion",
    btn_settings: "Paramètres",
    title_history: "Historique",
    title_budget: "Budget",
    title_compare: "Comparer les prix",
    title_ticket: "Votre ticket",
    btn_copy: "Copier",
    btn_whatsapp: "WhatsApp →",
    lbl_archive: "ARCHIVER L'ACHAT",
    plc_store: "Nom du magasin (ex: Carrefour…)",
    btn_save_history: "ENREGISTRER DANS L'HISTORIQUE",
    lbl_edit_item: "MODIFIER L'ARTICLE",
    btn_save: "ENREGISTRER",
    err_fill_all: "Remplissez l'e-mail et le mot de passe",
    err_login: "Erreur : ",
    alert_copied: "Copié dans le presse-papiers",
    alert_undo: "Annuler",
    alert_deleted: "supprimé",
    confirm_del_history: "Supprimer cet enregistrement de l'historique ?",
    btn_cancel: "Annuler",
    btn_delete: "Oui, supprimer",
    lbl_language: "LANGUE",
    lbl_currency: "DEVISE",
    btn_clear_cache: "EFFACER LE CACHE LOCAL",
    settings_title: "Paramètres",
    lbl_theme: "THÈME VISUEL",
    theme_light: "Clair",
    theme_dark: "Sombre"
  },
  de: {
    loading: "LÄDT...",
    btn_google: "Weiter mit Google",
    btn_email: "E-Mail und Passwort",
    btn_guest: "Als Gast fortfahren",
    lbl_email: "E-MAIL",
    plc_email: "du@email.com",
    lbl_password: "PASSWORT",
    plc_password: "******",
    btn_login: "ANMELDEN",
    btn_register: "REGISTRIEREN",
    btn_back: "← Zurück",
    lbl_name: "DEIN NAME",
    plc_name: "z.B.: Max",
    btn_login_anon: "ALS GAST EINTRETEN",
    offline_banner: "OFFLINE",
    receipt_title: "—— EINKAUFSLISTE ——",
    lbl_add_item: "+ NEUER ARTIKEL",
    plc_item_name: "Produkt…",
    plc_item_price: "Preis",
    plc_item_qty: "Menge",
    btn_add: "HINZUFÜGEN ›",
    empty_list: "— LEERE LISTE —",
    lbl_subtotal: "ZWISCHENSUMME",
    lbl_items: "ARTIKEL",
    lbl_open: "OFFEN",
    lbl_discount: "RABATT",
    lbl_total: "GESAMT",
    lbl_budget: "MONATSBUDGET",
    btn_finish: "EINKAUF BEENDEN",
    receipt_footer: "★ ★ ★ DANKE FÜR DIE NUTZUNG VON LISTBUY ★ ★ ★",
    btn_logout: "Abmelden",
    btn_settings: "Einstellungen",
    title_history: "Verlauf",
    title_budget: "Budget",
    title_compare: "Preise vergleichen",
    title_ticket: "Dein Bon",
    btn_copy: "Kopieren",
    btn_whatsapp: "WhatsApp →",
    lbl_archive: "EINKAUF ARCHIVIEREN",
    plc_store: "Geschäftsname (z.B.: Aldi…)",
    btn_save_history: "IM VERLAUF SPEICHERN",
    lbl_edit_item: "ARTIKEL BEARBEITEN",
    btn_save: "SPEICHERN",
    err_fill_all: "E-Mail und Passwort eingeben",
    err_login: "Fehler: ",
    alert_copied: "In die Zwischenablage kopiert",
    alert_undo: "Rückgängig",
    alert_deleted: "gelöscht",
    confirm_del_history: "Diesen Eintrag aus dem Verlauf löschen?",
    btn_cancel: "Abbrechen",
    btn_delete: "Ja, löschen",
    lbl_language: "SPRACHE",
    lbl_currency: "WÄHRUNG",
    btn_clear_cache: "LOKALEN CACHE LÖSCHEN",
    settings_title: "Einstellungen",
    lbl_theme: "THEMA",
    theme_light: "Hell",
    theme_dark: "Dunkel"
  }
};

let currentLang = localStorage.getItem('lb_lang') || 'es';
let currentCurrency = localStorage.getItem('lb_currency') || '$';

function setLanguage(lang) {
  if (!dict[lang]) return;
  currentLang = lang;
  localStorage.setItem('lb_lang', lang);
  applyTranslations();
}

function setCurrency(curr) {
  currentCurrency = curr;
  localStorage.setItem('lb_currency', curr);
  // Re-render UI elements using currency
  const prefixes = document.querySelectorAll('.price-prefix');
  prefixes.forEach(p => p.textContent = curr);
  if (typeof updateTotals === 'function') updateTotals();
}

function t(key) {
  return dict[currentLang][key] || dict['es'][key] || key;
}

function applyTranslations() {
  // Traducir todos los elementos con data-i18n (reemplaza texto)
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    el.textContent = t(key);
  });

  // Traducir los placeholders
  document.querySelectorAll('[data-i18n-plc]').forEach(el => {
    const key = el.getAttribute('data-i18n-plc');
    el.placeholder = t(key);
  });
  
  // Si la función initSettings está en app.js y ya cargó, re-renderiza el drawer
  if (typeof renderDrawerMenu === 'function') {
    renderDrawerMenu();
  }
}

// Ejecutar inmediatamente en la carga para traducir el HTML
document.addEventListener('DOMContentLoaded', () => {
  applyTranslations();
  setCurrency(currentCurrency);
});
